name = "star_demo_core"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Nathan Rignall"]
maintainers = ["Nathan Rignall <rignallnathan@gmail.com>"]
maintainers-logins = ["NathanRignall"]

executables = ["star_demo_core"]

[environment]
DEVICE_IDENTIFIER.set = "89"
CLOUD_BROADCAST_ADDRESS.set = "010.000.001.255"
RADIO_BROADCAST_ADDRESS.set = "172.000.001.255"