name = "star_demo_core"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Nathan Rignall"]
maintainers = ["Nathan Rignall <rignallnathan@gmail.com>"]
maintainers-logins = ["NathanRignall"]

executables = ["star_demo_core"]

[build-switches]
"*".style_checks = "No"
"*".Ada_Version = "Ada2022"

[environment]
DEVICE_IDENTIFIER.set = "89"
RADIO_MULTICAST_ADDRESS.set = "239.255.128.127"
CLOUD_MULTICAST_ADDRESS.set = "239.255.128.128"