version: "3"

services:
  drone1:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=11
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=52.0
      - INITIAL_LONGITUDE=0.0
      - INITIAL_VELOCITY_X=400
      - INITIAL_VELOCITY_Y=0
    networks:
      - system
  drone2:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=12
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=52.0
      - INITIAL_LONGITUDE=0.1
      - INITIAL_VELOCITY_X=0
      - INITIAL_VELOCITY_Y=300
    networks:
      - system
  drone3:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=13
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=52.0
      - INITIAL_LONGITUDE=-0.1
      - INITIAL_VELOCITY_X=0
      - INITIAL_VELOCITY_Y=-300
    networks:
      - system
  drone4:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=14
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=51.98
      - INITIAL_LONGITUDE=-1.36
      - INITIAL_VELOCITY_X=300
      - INITIAL_VELOCITY_Y=0
    networks:
      - system
  drone5:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=15
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=51.99
      - INITIAL_LONGITUDE=-1.38
      - INITIAL_VELOCITY_X=300
      - INITIAL_VELOCITY_Y=0
    networks:
      - system
  drone6:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=16
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=52.0
      - INITIAL_LONGITUDE=-1.4
      - INITIAL_VELOCITY_X=300
      - INITIAL_VELOCITY_Y=0
    networks:
      - system
  drone7:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=17
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=51.985
      - INITIAL_LONGITUDE=-1.4
      - INITIAL_VELOCITY_X=300
      - INITIAL_VELOCITY_Y=0
    networks:
      - system
  drone8:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=18
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=51.99
      - INITIAL_LONGITUDE=-1.42
      - INITIAL_VELOCITY_X=300
      - INITIAL_VELOCITY_Y=0
    networks:
      - system
  drone9:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=19
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
      - INITIAL_LATITUDE=51.98
      - INITIAL_LONGITUDE=-1.44
      - INITIAL_VELOCITY_X=300
      - INITIAL_VELOCITY_Y=0
    networks:
      - system

networks:
  system:
    driver: bridge