version: "3"

services:
  drone1:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=11
      - RADIO_ADDRESS=172.000.001.011
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_ADDRESS=010.000.001.011
      - CLOUD_MULTICAST_ADDRESS=239.255.128.128
    networks:
      radio:
        ipv4_address: 172.0.1.11
        priority: 1000
      cloud:
        ipv4_address: 10.0.1.11
        priority: 900
  drone2:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=12
      - RADIO_ADDRESS=172.000.001.012
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_ADDRESS=010.000.001.012
      - CLOUD_MULTICAST_ADDRESS=239.255.128.128
    networks:
      radio:
        ipv4_address: 172.0.1.12
        priority: 1000
      cloud:
        ipv4_address: 10.0.1.12
        priority: 900
  drone3:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=13
      - RADIO_ADDRESS=172.000.001.013
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_ADDRESS=010.000.001.013
      - CLOUD_MULTICAST_ADDRESS=239.255.128.128
    networks:
      radio:
        ipv4_address: 172.0.1.13
        priority: 1000
      cloud:
        ipv4_address: 10.0.1.13
        priority: 900
  drone4:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=14
      - RADIO_ADDRESS=172.000.001.014
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_ADDRESS=010.000.001.014
      - CLOUD_MULTICAST_ADDRESS=239.255.128.128
    networks:
      radio:
        ipv4_address: 172.0.1.14
        priority: 1000
      cloud:
        ipv4_address: 10.0.1.14
        priority: 900
  drone5:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=15
      - RADIO_ADDRESS=172.000.001.015
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_ADDRESS=010.000.001.015
      - CLOUD_MULTICAST_ADDRESS=239.255.128.128
    networks:
      radio:
        ipv4_address: 172.0.1.15
        priority: 1000
      cloud:
        ipv4_address: 10.0.1.15
        priority: 900

  # wireshark:
  #   image: lscr.io/linuxserver/wireshark:latest
  #   container_name: wireshark
  #   cap_add:
  #     - NET_ADMIN
  #   security_opt:
  #     - seccomp:unconfined
  #   networks:
  #     - radio
  #     - cloud
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped

networks:
  radio:
    driver: bridge
    ipam:
     config:
       - subnet: 172.0.1.0/24
  cloud:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/24
         gateway: 10.0.1.1