version: "3"

services:
  drone1:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=10
      - CLOUD_ADDRESS=010.000.001.010
      - CLOUD_BROADCAST_ADDRESS=010.000.001.255
      - RADIO_ADDRESS=172.000.001.010
      - RADIO_BROADCAST_ADDRESS=172.000.001.255
    networks:
      cloud:
        ipv4_address: 10.0.1.10
      radio:
        ipv4_address: 172.0.1.10
  drone2:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=11
      - CLOUD_ADDRESS=010.000.001.011
      - CLOUD_BROADCAST_ADDRESS=010.000.001.255
      - RADIO_ADDRESS=172.000.001.011
      - RADIO_BROADCAST_ADDRESS=172.000.001.255
    networks:
      cloud:
        ipv4_address: 10.0.1.11
      radio:
        ipv4_address: 172.0.1.11
  drone3:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=12
      - CLOUD_ADDRESS=010.000.001.012
      - CLOUD_BROADCAST_ADDRESS=010.000.001.255
      - RADIO_ADDRESS=172.000.001.012
      - RADIO_BROADCAST_ADDRESS=172.000.001.255
    networks:
      cloud:
        ipv4_address: 10.0.1.12
      radio:
        ipv4_address: 172.0.1.12

  # wireshark:
  #   image: lscr.io/linuxserver/wireshark:latest
  #   container_name: wireshark
  #   cap_add:
  #     - NET_ADMIN
  #   security_opt:
  #     - seccomp:unconfined
  #   networks:
  #     - radio
  #     - cloud
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped

networks:
  cloud:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.1.0/24
         gateway: 10.0.1.1
  radio:
    driver: bridge
    ipam:
     config:
       - subnet: 172.0.1.0/24
  