version: "3"

services:
  drone1:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=11
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone2:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=12
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone3:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=13
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone4:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=14
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone5:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=15
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone6:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=16
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone7:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=17
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone8:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=18
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system
  drone9:
    image: stardemocore:dev
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - DEVICE_IDENTIFIER=19
      - RADIO_MULTICAST_ADDRESS=239.255.128.127
      - CLOUD_SERVER_ADDRESS=172.020.000.002
    networks:
      - system

  # wireshark:
  #   image: lscr.io/linuxserver/wireshark:latest
  #   container_name: wireshark
  #   cap_add:
  #     - NET_ADMIN
  #   security_opt:
  #     - seccomp:unconfined
  #   networks:
  #     - system
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   ports:
  #     - 3000:3000
  #   restart: unless-stopped

networks:
  system:
    driver: bridge